# Generated by Django 2.0.1 on 2018-02-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractRiskFieldType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DateRiskField',
            fields=[
                ('abstractriskfieldtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractRiskFieldType')),
                ('minDate', models.DateField(null=True)),
                ('maxDate', models.DateField(null=True)),
            ],
            bases=('app.abstractriskfieldtype',),
        ),
        migrations.CreateModel(
            name='EnumRiskField',
            fields=[
                ('abstractriskfieldtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractRiskFieldType')),
                ('values', models.TextField()),
            ],
            bases=('app.abstractriskfieldtype',),
        ),
        migrations.CreateModel(
            name='NumberRiskField',
            fields=[
                ('abstractriskfieldtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractRiskFieldType')),
                ('minValue', models.FloatField(null=True)),
                ('maxValue', models.FloatField(null=True)),
            ],
            bases=('app.abstractriskfieldtype',),
        ),
        migrations.CreateModel(
            name='TextRiskField',
            fields=[
                ('abstractriskfieldtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.AbstractRiskFieldType')),
                ('minLength', models.IntegerField(null=True)),
                ('maxLength', models.IntegerField(null=True)),
            ],
            bases=('app.abstractriskfieldtype',),
        ),
        migrations.AddField(
            model_name='abstractriskfieldtype',
            name='content_type',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='abstractriskfieldtype',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.RiskType'),
        ),
    ]
