# Generated by Django 2.0.1 on 2018-02-01 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='RiskTypeField',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data_type', models.CharField(choices=[
                 ('t', 'Text'), ('n', 'Number'), ('d', 'Date'), ('e', 'Enum')], max_length=1)),
                ('risk_type', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='app.RiskType')),
            ],
        ),
    ]
