# Generated by Django 2.0.1 on 2018-02-03 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateriskfield',
            old_name='maxDate',
            new_name='max_date',
        ),
        migrations.RenameField(
            model_name='dateriskfield',
            old_name='minDate',
            new_name='min_date',
        ),
        migrations.RenameField(
            model_name='numberriskfield',
            old_name='maxValue',
            new_name='max_value',
        ),
        migrations.RenameField(
            model_name='numberriskfield',
            old_name='minValue',
            new_name='min_value',
        ),
        migrations.RenameField(
            model_name='textriskfield',
            old_name='maxLength',
            new_name='max_length',
        ),
        migrations.RenameField(
            model_name='textriskfield',
            old_name='minLength',
            new_name='min_length',
        ),
    ]
